 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/helps", type: :request do
  
  # Help. As you add validations to Help, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Help.create! valid_attributes
      get helps_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      help = Help.create! valid_attributes
      get help_url(help)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_help_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      help = Help.create! valid_attributes
      get edit_help_url(help)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Help" do
        expect {
          post helps_url, params: { help: valid_attributes }
        }.to change(Help, :count).by(1)
      end

      it "redirects to the created help" do
        post helps_url, params: { help: valid_attributes }
        expect(response).to redirect_to(help_url(Help.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Help" do
        expect {
          post helps_url, params: { help: invalid_attributes }
        }.to change(Help, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post helps_url, params: { help: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested help" do
        help = Help.create! valid_attributes
        patch help_url(help), params: { help: new_attributes }
        help.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the help" do
        help = Help.create! valid_attributes
        patch help_url(help), params: { help: new_attributes }
        help.reload
        expect(response).to redirect_to(help_url(help))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        help = Help.create! valid_attributes
        patch help_url(help), params: { help: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested help" do
      help = Help.create! valid_attributes
      expect {
        delete help_url(help)
      }.to change(Help, :count).by(-1)
    end

    it "redirects to the helps list" do
      help = Help.create! valid_attributes
      delete help_url(help)
      expect(response).to redirect_to(helps_url)
    end
  end
end
