require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/member_points', type: :request do
  # MemberPoint. As you add validations to MemberPoint, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      MemberPoint.create! valid_attributes
      get member_points_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      member_point = MemberPoint.create! valid_attributes
      get member_point_url(member_point)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_member_point_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      member_point = MemberPoint.create! valid_attributes
      get edit_member_point_url(member_point)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new MemberPoint' do
        expect do
          post member_points_url, params: { member_point: valid_attributes }
        end.to change(MemberPoint, :count).by(1)
      end

      it 'redirects to the created member_point' do
        post member_points_url, params: { member_point: valid_attributes }
        expect(response).to redirect_to(member_point_url(MemberPoint.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new MemberPoint' do
        expect do
          post member_points_url, params: { member_point: invalid_attributes }
        end.to change(MemberPoint, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post member_points_url, params: { member_point: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested member_point' do
        member_point = MemberPoint.create! valid_attributes
        patch member_point_url(member_point), params: { member_point: new_attributes }
        member_point.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the member_point' do
        member_point = MemberPoint.create! valid_attributes
        patch member_point_url(member_point), params: { member_point: new_attributes }
        member_point.reload
        expect(response).to redirect_to(member_point_url(member_point))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        member_point = MemberPoint.create! valid_attributes
        patch member_point_url(member_point), params: { member_point: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested member_point' do
      member_point = MemberPoint.create! valid_attributes
      expect do
        delete member_point_url(member_point)
      end.to change(MemberPoint, :count).by(-1)
    end

    it 'redirects to the member_points list' do
      member_point = MemberPoint.create! valid_attributes
      delete member_point_url(member_point)
      expect(response).to redirect_to(member_points_url)
    end
  end
end
